name: HEAL_isaacsim_full_lidar_disco
root_dir: dataset/IsaacSimOPV2V/train
validate_dir: dataset/IsaacSimOPV2V/validate
test_dir: dataset/IsaacSimOPV2V/test
yaml_parser: load_general_params
train_params:
  batch_size: 2
  epoches: 50
  eval_freq: 4
  save_freq: 4
  max_cav: 2
comm_range: 50
input_source:
- lidar
label_type: lidar
cav_lidar_range: &id001
- 0.0
- -11.2
- -1
- 22.4
- 11.2
- 3
add_data_extension: []
fusion:
  core_method: intermediateheter
  dataset: isaacsim
  args:
    proj_first: false
    grid_conf: None
    data_aug_conf: None
data_augment:
- NAME: random_world_flip
  ALONG_AXIS_LIST:
  - x
- NAME: random_world_rotation
  WORLD_ROT_ANGLE:
  - -0.39269908
  - 0.39269908
- NAME: random_world_scaling
  WORLD_SCALE_RANGE:
  - 0.95
  - 1.05
preprocess:
  core_method: SpVoxelPreprocessor
  args:
    voxel_size: &id002
    - 0.1
    - 0.1
    - 4
    max_points_per_voxel: 1
    max_voxel_train: 1
    max_voxel_test: 1
  cav_lidar_range: *id001
heter:
  assignment_path: dataset/IsaacSimOPV2V/heter_modality_assign.json
  ego_modality: m1
  mapping_dict:
    m1: m1
    m2: m1
  modality_setting:
    m1:
      sensor_type: lidar
      core_method: point_pillar
      preprocess:
        core_method: SpVoxelPreprocessor
        args:
          voxel_size: *id002
          max_points_per_voxel: 32
          max_voxel_train: 60000
          max_voxel_test: 120000
        cav_lidar_range: *id001
postprocess:
  core_method: VoxelPostprocessor
  gt_range: *id001
  anchor_args:
    cav_lidar_range: *id001
    l: 0.53
    w: 0.47
    h: 0.67
    r: &id003
    - 0
    - 90
    feature_stride: 2
    num: 2
  target_args:
    pos_threshold: 0.6
    neg_threshold: 0.45
    score_threshold: 0.2
  order: hwl
  max_num: 1024
  nms_thresh: 0.15
  dir_args: &id004
    dir_offset: 0.7853
    num_bins: 2
    anchor_yaw: *id003
model:
  core_method: heter_model_baseline
  args:
    ego_modality: m1
    lidar_range: *id001
    m1:
      core_method: point_pillar
      sensor_type: lidar
      encoder_args:
        voxel_size: *id002
        lidar_range: *id001
        pillar_vfe:
          use_norm: true
          with_distance: false
          use_absolute_xyz: true
          num_filters:
          - 64
        point_pillar_scatter:
          num_features: 64
      backbone_args:
        layer_nums:
        - 3
        - 5
        - 8
        layer_strides:
        - 2
        - 2
        - 2
        num_filters:
        - 64
        - 128
        - 256
        upsample_strides:
        - 1
        - 2
        - 4
        num_upsample_filter:
        - 128
        - 128
        - 128
      shrink_header:
        kernal_size:
        - 3
        stride:
        - 1
        padding:
        - 1
        dim:
        - 256
        input_dim: 384
    fusion_method: disconet
    in_head: 256
    anchor_number: 2
    dir_args: *id004
    disconet:
      feat_dim: 256
loss:
  core_method: point_pillar_depth_loss
  args:
    pos_cls_weight: 2.0
    cls:
      type: SigmoidFocalLoss
      alpha: 0.25
      gamma: 2.0
      weight: 1.0
    reg:
      type: WeightedSmoothL1Loss
      sigma: 3.0
      codewise: true
      weight: 2.0
    dir:
      type: WeightedSoftmaxClassificationLoss
      weight: 0.2
      args:
        dir_offset: 0.7853
        num_bins: 2
        anchor_yaw: *id003
    depth:
      weight: 1.0
optimizer:
  core_method: AdamW
  lr: 0.001
  args:
    eps: 1.0e-08
    weight_decay: 0.01
lr_scheduler:
  core_method: multistep
  gamma: 0.1
  step_size:
  - 10
  - 25
